// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz91iVPJhaqxi-HbYlwH9hyJ9p8MK8v-c',
    appId: '1:1051647123848:web:7cf739d3991c8e90531a3d',
    messagingSenderId: '1051647123848',
    projectId: 'handzy-thozha',
    authDomain: 'handzy-thozha.firebaseapp.com',
    storageBucket: 'handzy-thozha.firebasestorage.app',
    measurementId: 'G-J19S3SGZ8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWSGXlXZVKRoUE68A4wFe_k6U_58ubG1E',
    appId: '1:1051647123848:android:3564a5ebf17ae692531a3d',
    messagingSenderId: '1051647123848',
    projectId: 'handzy-thozha',
    storageBucket: 'handzy-thozha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwfJ0jxglEU_z_VKp3EjKprKA3XmPmXfk',
    appId: '1:1051647123848:ios:ef3dcaf82818be36531a3d',
    messagingSenderId: '1051647123848',
    projectId: 'handzy-thozha',
    storageBucket: 'handzy-thozha.firebasestorage.app',
    iosBundleId: 'com.handzy.thozhan',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwfJ0jxglEU_z_VKp3EjKprKA3XmPmXfk',
    appId: '1:1051647123848:ios:7b5f980e02bce1c6531a3d',
    messagingSenderId: '1051647123848',
    projectId: 'handzy-thozha',
    storageBucket: 'handzy-thozha.firebasestorage.app',
    iosBundleId: 'com.example.handzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz91iVPJhaqxi-HbYlwH9hyJ9p8MK8v-c',
    appId: '1:1051647123848:web:e6d25bbed8e00cea531a3d',
    messagingSenderId: '1051647123848',
    projectId: 'handzy-thozha',
    authDomain: 'handzy-thozha.firebaseapp.com',
    storageBucket: 'handzy-thozha.firebasestorage.app',
    measurementId: 'G-D0KG4273ZW',
  );
}
